//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BinhLuan
    {
        [Key]
        public int MaBL { get; set; }
        public string NoidungBL { get; set; }
        public Nullable<int> MaThanhVien { get; set; }
        public Nullable<int> MaSP { get; set; }

        [ForeignKey("MaSP")]

        public virtual SanPham SanPham { get; set; }

        [ForeignKey("MaThanhVien")]

        public virtual ThanhVien ThanhVien { get; set; }
    }
}
